INSERT INTO Branch(branch_id, name, city, district, address)
VALUES
('0001', 'Lì Měi Weiyang Flagship', 'Xian', 'Weiyang District', '029 Stephen Corner Apt. 499 (Near University)'),
('0002', 'Yī Zhào Wéi Dé Yuexiu Flagship', 'Guangzhou', 'Yuexiu District', '61338 Tammy Extension Suite 727 (Near Metro Station)'),
('0003', 'Jiàn Lè Zhongyuan Flagship', 'Zhengzhou', 'Zhongyuan District', '98660 Zachary Cliff (Near University)'),
('0004', 'Lì Měi Chancheng Flagship', 'Foshan', 'Chancheng District', '5262 Deborah Locks Suite 602 (Near Shopping Mall)'),
('0005', 'Yī Zhào Wéi Dé Beilun Flagship', 'Ningbo', 'Beilun District', '72081 Elliott Neck Apt. 562 (Near University)'),
('0006', 'Jīn Shì Bǎo Putuo Flagship', 'Shanghai', 'Putuo District', '845 Moore Cape Suite 790 (Near University)'),
('0007', 'Lì Měi Hanyang Flagship', 'Wuhan', 'Hanyang District', '75822 Rogers Skyway Suite 282 (Near Shopping Mall)'),
('0008', 'Wēi Ěr Shì Yantian Flagship', 'Shenzhen', 'Yantian District', '150 Kenneth Pine (Near University)'),
('0009', 'Jiàn Lè Gaoming Flagship', 'Foshan', 'Gaoming District', '108 Mason Circle (Near Metro Station)'),
('0010', 'Wēi Ěr Shì Huangpu Flagship', 'Shanghai', 'Huangpu District', '19871 Sherry Mountains Apt. 570 (Near University)'),
('0011', 'Ào Měi Jianye Flagship', 'Nanjing', 'Jianye District', '651 Wolfe Run (Near Metro Station)'),
('0012', 'Wēi Ěr Shì Hongkou Flagship', 'Shanghai', 'Hongkou District', '6166 Booker Drives Suite 844 (Near Shopping Mall)'),
('0013', 'Wēi Ěr Shì Jianye Flagship', 'Nanjing', 'Jianye District', '8279 Rebecca Field Suite 156 (Near Metro Station)'),
('0014', 'Wēi Ěr Shì Zhongshan Flagship', 'Dalian', 'Zhongshan District', '5018 Elizabeth Lakes (Near Shopping Mall)'),
('0015', 'Měi Gé Fēi Luohu Flagship', 'Shenzhen', 'Luohu District', '9567 Janet Shoal Apt. 625 (Near Shopping Mall)'),
('0016', 'Jiàn Lè Baiyun Flagship', 'Guangzhou', 'Baiyun District', '057 Tina Gateway Suite 814 (Near University)'),
('0017', 'Lì Měi Xinwu Flagship', 'Wuxi', 'Xinwu District', '633 Ryan Port Suite 950 (Near University)'),
('0018', 'Měi Gé Fēi Xicheng Flagship', 'Beijing', 'Xicheng District', '9876 Lisa Flat Suite 151 (Near Shopping Mall)'),
('0019', 'Wēi Kāng Baoan Flagship', 'Shenzhen', 'Baoan District', '977 Brown Locks Suite 763 (Near University)'),
('0020', 'Ào Měi Jiangbei Flagship', 'Chongqing', 'Jiangbei District', '4769 Tracy Overpass (Near Shopping Mall)'),
('0021', 'Wēi Kāng Dongcheng Flagship', 'Beijing', 'Dongcheng District', '8215 Mitchell Ranch Apt. 947 (Near Metro Station)'),
('0022', 'Wēi Kāng Shahekou Flagship', 'Dalian', 'Shahekou District', '670 Solis Spur (Near Metro Station)'),
('0023', 'Lì Měi Liwan Flagship', 'Guangzhou', 'Liwan District', '14972 Miller Forge (Near Shopping Mall)'),
('0024', 'Jīn Shì Bǎo Xihu Flagship', 'Hangzhou', 'Xihu District', '4295 David Circles (Near Shopping Mall)'),
('0025', 'Jīn Shì Bǎo Shinan Flagship', 'Qingdao', 'Shinan District', '4357 Scott Loaf Apt. 736 (Near University)'),
('0026', 'Yī Zhào Wéi Dé Yantian Flagship', 'Shenzhen', 'Yantian District', '5197 Robinson Rue (Near Metro Station)'),
('0027', 'Jīn Shì Bǎo Yuzhong Flagship', 'Chongqing', 'Yuzhong District', '243 Andersen Forest Suite 429 (Near Shopping Mall)'),
('0028', 'Yī Zhào Wéi Dé Xihu Flagship', 'Hangzhou', 'Xihu District', '695 Foster Place (Near Metro Station)'),
('0029', 'Wēi Ěr Shì Heping Flagship', 'Tianjin', 'Heping District', '98276 Sara Roads (Near University)'),
('0030', 'Wēi Kāng Xuhui Flagship', 'Shanghai', 'Xuhui District', '077 Brandon Roads (Near Shopping Mall)'),
('0031', 'Wēi Ěr Shì Xinwu Flagship', 'Wuxi', 'Xinwu District', '4210 John Road Apt. 853 (Near Metro Station)'),
('0032', 'Jīn Shì Bǎo Jiangan Flagship', 'Wuhan', 'Jiangan District', '7213 Michael Trail Apt. 020 (Near Metro Station)'),
('0033', 'Lì Měi Erqi Flagship', 'Zhengzhou', 'Erqi District', '193 Bruce Cove (Near Shopping Mall)'),
('0034', 'Jiàn Lè Liangxi Flagship', 'Wuxi', 'Liangxi District', '114 Davis Path (Near Metro Station)'),
('0035', 'Jīn Shì Bǎo Fenghua Flagship', 'Ningbo', 'Fenghua District', '2511 Chavez Isle Suite 611 (Near Shopping Mall)'),
('0036', 'Lì Měi Tongzhou Flagship', 'Beijing', 'Tongzhou District', '254 Mullins Prairie Apt. 003 (Near Shopping Mall)'),
('0037', 'Ào Měi Shunde Flagship', 'Foshan', 'Shunde District', '68841 Baxter Stream Apt. 993 (Near Metro Station)'),
('0038', 'Lì Měi Jiulongpo Flagship', 'Chongqing', 'Jiulongpo District', '156 Williams Station Apt. 378 (Near Metro Station)'),
('0039', 'Měi Gé Fēi Shijingshan Flagship', 'Beijing', 'Shijingshan District', '07933 Amber Pass (Near Shopping Mall)'),
('0040', 'Yī Zhào Wéi Dé Liangxi Flagship', 'Wuxi', 'Liangxi District', '4634 Barber Common (Near Shopping Mall)'),
('0041', 'Yī Zhào Wéi Dé Baiyun Flagship', 'Guangzhou', 'Baiyun District', '383 Michael Underpass Suite 090 (Near University)'),
('0042', 'Ào Měi Huangpu Flagship', 'Guangzhou', 'Huangpu District', '6451 Jason Wall Suite 292 (Near Shopping Mall)'),
('0043', 'Lì Měi Yantian Flagship', 'Shenzhen', 'Yantian District', '080 Bruce Summit Suite 114 (Near Metro Station)'),
('0044', 'Lì Měi Jiulongpo Flagship', 'Chongqing', 'Jiulongpo District', '9406 Reed Extension Apt. 198 (Near Shopping Mall)'),
('0045', 'Jiàn Lè Changqing Flagship', 'Jinan', 'Changqing District', '583 Anthony Mountain Apt. 393 (Near Shopping Mall)'),
('0046', 'Wēi Kāng Hedong Flagship', 'Tianjin', 'Hedong District', '63442 Jennifer Inlet Suite 896 (Near University)'),
('0047', 'Yī Zhào Wéi Dé Yuhuatai Flagship', 'Nanjing', 'Yuhuatai District', '3784 Brooke Roads Apt. 540 (Near University)'),
('0048', 'Měi Gé Fēi Putuo Flagship', 'Shanghai', 'Putuo District', '5098 Woods Extensions (Near University)'),
('0049', 'Lì Měi Tianqiao Flagship', 'Jinan', 'Tianqiao District', '4805 Smith Harbor (Near Metro Station)'),
('0050', 'Wēi Ěr Shì Wangcheng Flagship', 'Changsha', 'Wangcheng District', '398 Steven Expressway Apt. 760 (Near Shopping Mall)'),
('0051', 'Ào Měi Jinjiang Flagship', 'Chengdu', 'Jinjiang District', '949 Carlos Shore Apt. 762 (Near University)'),
('0052', 'Měi Gé Fēi Yanta Flagship', 'Xian', 'Yanta District', '9849 Jones Divide (Near University)'),
('0053', 'Yī Zhào Wéi Dé Dongcheng Flagship', 'Beijing', 'Dongcheng District', '8717 Powell Loop Apt. 026 (Near Shopping Mall)'),
('0054', 'Jiàn Lè Xiacheng Flagship', 'Hangzhou', 'Xiacheng District', '04847 Antonio Extensions (Near Metro Station)'),
('0055', 'Wēi Ěr Shì Siming Flagship', 'Xiamen', 'Siming District', '353 Terry Drive Apt. 236 (Near University)'),
('0056', 'Yī Zhào Wéi Dé Lianhu Flagship', 'Xian', 'Lianhu District', '626 Clark Curve Apt. 053 (Near University)'),
('0057', 'Jīn Shì Bǎo Shijingshan Flagship', 'Beijing', 'Shijingshan District', '961 Burgess Center Suite 994 (Near University)'),
('0058', 'Wēi Kāng Xishan Flagship', 'Wuxi', 'Xishan District', '507 Hamilton Village Suite 195 (Near Shopping Mall)'),
('0059', 'Jīn Shì Bǎo Weiyang Flagship', 'Xian', 'Weiyang District', '865 Juan Ford (Near Shopping Mall)'),
('0060', 'Ào Měi Haishu Flagship', 'Ningbo', 'Haishu District', '2285 Taylor Estate (Near Shopping Mall)'),
('0061', 'Lì Měi Nankai Flagship', 'Tianjin', 'Nankai District', '84335 April Dale (Near Metro Station)'),
('0062', 'Yī Zhào Wéi Dé Xiacheng Flagship', 'Hangzhou', 'Xiacheng District', '770 Williams Roads Apt. 765 (Near Metro Station)'),
('0063', 'Yī Zhào Wéi Dé Sanshui Flagship', 'Foshan', 'Sanshui District', '2814 Krueger Flats Suite 989 (Near Shopping Mall)'),
('0064', 'Wēi Ěr Shì Jiulongpo Flagship', 'Chongqing', 'Jiulongpo District', '861 Julie Dam Suite 051 (Near Metro Station)'),
('0065', 'Lì Měi Haizhu Flagship', 'Guangzhou', 'Haizhu District', '4676 Luke Wall Apt. 984 (Near Shopping Mall)'),
('0066', 'Lì Měi Nanan Flagship', 'Chongqing', 'Nanan District', '8746 Brandt Crest (Near University)'),
('0067', 'Jīn Shì Bǎo Yangpu Flagship', 'Shanghai', 'Yangpu District', '35861 David Stream Suite 785 (Near University)'),
('0068', 'Jiàn Lè Huaiyin Flagship', 'Jinan', 'Huaiyin District', '42331 Chad Rapid Apt. 811 (Near University)'),
('0069', 'Wēi Ěr Shì Xuanwu Flagship', 'Nanjing', 'Xuanwu District', '1264 West Radial Suite 926 (Near Shopping Mall)'),
('0070', 'Wēi Kāng Chaoyang Flagship', 'Beijing', 'Chaoyang District', '46533 Johnson Shoal (Near University)'),
('0071', 'Jīn Shì Bǎo Hexi Flagship', 'Tianjin', 'Hexi District', '84065 Lewis Ports Suite 553 (Near University)'),
('0072', 'Měi Gé Fēi Hongqiao Flagship', 'Tianjin', 'Hongqiao District', '5063 Rivers Crest (Near University)'),
('0073', 'Měi Gé Fēi Shunde Flagship', 'Foshan', 'Shunde District', '228 Michael Drive (Near Metro Station)'),
('0074', 'Ào Měi Xiacheng Flagship', 'Hangzhou', 'Xiacheng District', '4841 Frances Spring (Near University)'),
('0075', 'Ào Měi Xicheng Flagship', 'Beijing', 'Xicheng District', '790 Anthony Mall Apt. 955 (Near Metro Station)'),
('0076', 'Jiàn Lè Jinjiang Flagship', 'Chengdu', 'Jinjiang District', '78948 Castro Estate (Near University)'),
('0077', 'Wēi Kāng Chaoyang Flagship', 'Beijing', 'Chaoyang District', '99778 Maria Lake (Near Shopping Mall)'),
('0078', 'Lì Měi Hongkou Flagship', 'Shanghai', 'Hongkou District', '87693 Christine Spur Apt. 580 (Near Metro Station)'),
('0079', 'Wēi Ěr Shì Tianxin Flagship', 'Changsha', 'Tianxin District', '4012 Tiffany Fork Suite 243 (Near University)'),
('0080', 'Wēi Kāng Wuzhong Flagship', 'Suzhou', 'Wuzhong District', '3234 Harrington Dale (Near Metro Station)'),
('0081', 'Jiàn Lè Jinshui Flagship', 'Zhengzhou', 'Jinshui District', '614 Morris Glen Apt. 284 (Near Shopping Mall)'),
('0082', 'Ào Měi Chenghua Flagship', 'Chengdu', 'Chenghua District', '0955 Richard Vista (Near Metro Station)'),
('0083', 'Měi Gé Fēi Hongkou Flagship', 'Shanghai', 'Hongkou District', '653 Gregory Island Apt. 867 (Near Metro Station)'),
('0084', 'Jīn Shì Bǎo Futian Flagship', 'Shenzhen', 'Futian District', '533 John Highway (Near University)'),
('0085', 'Lì Měi Zhongshan Flagship', 'Dalian', 'Zhongshan District', '82180 Kathy Roads Suite 181 (Near Metro Station)'),
('0086', 'Yī Zhào Wéi Dé Xincheng Flagship', 'Xian', 'Xincheng District', '5578 Peter Burg (Near Shopping Mall)'),
('0087', 'Ào Měi Nanhai Flagship', 'Foshan', 'Nanhai District', '85107 Brock Camp Apt. 651 (Near Metro Station)'),
('0088', 'Lì Měi Songshanhu Flagship', 'Dongguan', 'Songshanhu District', '603 Davis Stravenue Apt. 271 (Near University)'),
('0089', 'Jiàn Lè Shapingba Flagship', 'Chongqing', 'Shapingba District', '07969 Richard Trace (Near Shopping Mall)'),
('0090', 'Wēi Ěr Shì Beibei Flagship', 'Chongqing', 'Beibei District', '2876 Pratt Parkway Suite 774 (Near University)'),
('0091', 'Měi Gé Fēi Liangxi Flagship', 'Wuxi', 'Liangxi District', '6230 Arroyo Fields (Near Shopping Mall)'),
('0092', 'Wēi Kāng Jinniu Flagship', 'Chengdu', 'Jinniu District', '771 Stein Mill (Near Shopping Mall)'),
('0093', 'Jiàn Lè Siming Flagship', 'Xiamen', 'Siming District', '93685 Bennett Hill (Near University)'),
('0094', 'Yī Zhào Wéi Dé Liwan Flagship', 'Guangzhou', 'Liwan District', '80708 West Lock (Near Metro Station)'),
('0095', 'Wēi Kāng Jianye Flagship', 'Nanjing', 'Jianye District', '9409 Bruce Mission (Near Metro Station)'),
('0096', 'Yī Zhào Wéi Dé Shangjie Flagship', 'Zhengzhou', 'Shangjie District', '4984 Samantha Spur (Near Metro Station)'),
('0097', 'Jīn Shì Bǎo Tongzhou Flagship', 'Beijing', 'Tongzhou District', '99735 Monica Springs (Near Shopping Mall)'),
('0098', 'Lì Měi Tongzhou Flagship', 'Beijing', 'Tongzhou District', '115 Shelton Port Suite 812 (Near University)'),
('0099', 'Yī Zhào Wéi Dé Yantian Flagship', 'Shenzhen', 'Yantian District', '949 Kelly Mission Suite 804 (Near Shopping Mall)'),
('0100', 'Wēi Ěr Shì Tongzhou Flagship', 'Beijing', 'Tongzhou District', '596 Wise Port (Near Metro Station)'),
('0101', 'Lì Měi Yangpu Flagship', 'Shanghai', 'Yangpu District', '0506 Gilbert Oval (Near University)'),
('0102', 'Wēi Kāng Baiyun Flagship', 'Guangzhou', 'Baiyun District', '09015 Nelson Way (Near University)'),
('0103', 'Wēi Ěr Shì Fengtai Flagship', 'Beijing', 'Fengtai District', '2761 Fry Crossing (Near Shopping Mall)'),
('0104', 'Wēi Kāng Liangxi Flagship', 'Wuxi', 'Liangxi District', '6941 Jessica Freeway Suite 729 (Near University)'),
('0105', 'Jīn Shì Bǎo Nanan Flagship', 'Chongqing', 'Nanan District', '41668 Roberts Hills (Near University)'),
('0106', 'Ào Měi Xicheng Flagship', 'Beijing', 'Xicheng District', '7252 Martinez Via Suite 170 (Near Metro Station)'),
('0107', 'Yī Zhào Wéi Dé Lianhu Flagship', 'Xian', 'Lianhu District', '567 Kelly Landing Suite 370 (Near Shopping Mall)'),
('0108', 'Wēi Kāng Yantian Flagship', 'Shenzhen', 'Yantian District', '41181 Alison Street (Near Metro Station)'),
('0109', 'Jīn Shì Bǎo Guancheng Flagship', 'Zhengzhou', 'Guancheng District', '225 Sullivan Plains (Near Metro Station)'),
('0110', 'Ào Měi Yuexiu Flagship', 'Guangzhou', 'Yuexiu District', '423 John Harbor Apt. 798 (Near Metro Station)'),
('0111', 'Jīn Shì Bǎo Shangcheng Flagship', 'Hangzhou', 'Shangcheng District', '24947 Hoffman Curve (Near University)'),
('0112', 'Yī Zhào Wéi Dé Xishan Flagship', 'Wuxi', 'Xishan District', '97538 Miller Corner Suite 227 (Near Shopping Mall)'),
('0113', 'Wēi Ěr Shì Guancheng Flagship', 'Dongguan', 'Guancheng District', '587 Clark Passage Suite 944 (Near Shopping Mall)'),
('0114', 'Měi Gé Fēi Liwan Flagship', 'Guangzhou', 'Liwan District', '27691 Jeremy Tunnel Suite 542 (Near University)'),
('0115', 'Ào Měi Tianhe Flagship', 'Guangzhou', 'Tianhe District', '84061 Robert Square (Near Metro Station)'),
('0116', 'Jīn Shì Bǎo Siming Flagship', 'Xiamen', 'Siming District', '4821 Marc Route Apt. 624 (Near Metro Station)'),
('0117', 'Měi Gé Fēi Lixia Flagship', 'Jinan', 'Lixia District', '0063 Smith Expressway Apt. 718 (Near University)'),
('0118', 'Jīn Shì Bǎo Xincheng Flagship', 'Xian', 'Xincheng District', '28223 Allen Trace (Near University)'),
('0119', 'Jiàn Lè Industrial Flagship', 'Suzhou', 'Industrial Park District', '15620 Alexis Valleys (Near Metro Station)'),
('0120', 'Jiàn Lè Xiacheng Flagship', 'Hangzhou', 'Xiacheng District', '995 Sean Camp (Near University)'),
('0121', 'Jīn Shì Bǎo Qixia Flagship', 'Nanjing', 'Qixia District', '1572 Meredith Springs (Near University)'),
('0122', 'Yī Zhào Wéi Dé Xinwu Flagship', 'Wuxi', 'Xinwu District', '5530 Marilyn Park Apt. 294 (Near Metro Station)'),
('0123', 'Lì Měi Baoan Flagship', 'Shenzhen', 'Baoan District', '0693 John Greens (Near Metro Station)'),
('0124', 'Wēi Kāng Binjiang Flagship', 'Hangzhou', 'Binjiang District', '267 Emily Ranch (Near Shopping Mall)'),
('0125', 'Yī Zhào Wéi Dé Xiangcheng Flagship', 'Suzhou', 'Xiangcheng District', '42927 Robert Way (Near Metro Station)'),
('0126', 'Wēi Kāng Gusu Flagship', 'Suzhou', 'Gusu District', '4429 Austin Roads (Near Shopping Mall)'),
('0127', 'Jīn Shì Bǎo Yantian Flagship', 'Shenzhen', 'Yantian District', '67264 Jared Skyway (Near Metro Station)'),
('0128', 'Yī Zhào Wéi Dé Shangcheng Flagship', 'Hangzhou', 'Shangcheng District', '17633 Kelly Bridge Apt. 436 (Near Metro Station)'),
('0129', 'Jīn Shì Bǎo Jinjiang Flagship', 'Chengdu', 'Jinjiang District', '1966 Lisa Forest (Near Metro Station)'),
('0130', 'Yī Zhào Wéi Dé Tianhe Flagship', 'Guangzhou', 'Tianhe District', '26026 Sarah Mews Apt. 590 (Near Metro Station)'),
('0131', 'Jīn Shì Bǎo Lianhu Flagship', 'Xian', 'Lianhu District', '5519 Shawn Stream Apt. 093 (Near Shopping Mall)'),
('0132', 'Jiàn Lè Zhongshan Flagship', 'Dalian', 'Zhongshan District', '9790 Beard Neck Suite 470 (Near Metro Station)'),
('0133', 'Jīn Shì Bǎo Fengtai Flagship', 'Beijing', 'Fengtai District', '788 Ross Locks (Near University)'),
('0134', 'Měi Gé Fēi Lixia Flagship', 'Jinan', 'Lixia District', '6865 Michael Pike Suite 576 (Near Shopping Mall)'),
('0135', 'Lì Měi Dongcheng Flagship', 'Dongguan', 'Dongcheng District', '821 Gloria Lakes (Near University)'),
('0136', 'Jiàn Lè Luohu Flagship', 'Shenzhen', 'Luohu District', '02764 Heather Place Apt. 571 (Near University)'),
('0137', 'Wēi Ěr Shì Ganjingzi Flagship', 'Dalian', 'Ganjingzi District', '80922 Carlos Mountain Apt. 690 (Near University)'),
('0138', 'Ào Měi Jiangan Flagship', 'Wuhan', 'Jiangan District', '74492 Lyons Loaf (Near Metro Station)'),
('0139', 'Lì Měi Wangcheng Flagship', 'Changsha', 'Wangcheng District', '335 Christina Prairie (Near University)'),
('0140', 'Ào Měi Tianqiao Flagship', 'Jinan', 'Tianqiao District', '95197 Glenn Heights (Near Metro Station)'),
('0141', 'Yī Zhào Wéi Dé Yuzhong Flagship', 'Chongqing', 'Yuzhong District', '79021 Wise Roads (Near Metro Station)'),
('0142', 'Lì Měi Shangcheng Flagship', 'Hangzhou', 'Shangcheng District', '622 Christopher Glen Suite 129 (Near Shopping Mall)'),
('0143', 'Měi Gé Fēi Erqi Flagship', 'Zhengzhou', 'Erqi District', '71751 Amy Inlet Apt. 427 (Near Shopping Mall)'),
('0144', 'Jiàn Lè Gaoming Flagship', 'Foshan', 'Gaoming District', '437 Diaz Isle (Near University)'),
('0145', 'Měi Gé Fēi Sanshui Flagship', 'Foshan', 'Sanshui District', '96772 Wilson Groves (Near Shopping Mall)'),
('0146', 'Ào Měi Hongkou Flagship', 'Shanghai', 'Hongkou District', '5794 Powell Islands Apt. 960 (Near Metro Station)'),
('0147', 'Ào Měi Jianye Flagship', 'Nanjing', 'Jianye District', '005 Guerrero Center Apt. 271 (Near Shopping Mall)'),
('0148', 'Měi Gé Fēi Xincheng Flagship', 'Xian', 'Xincheng District', '23349 Autumn Parkway (Near University)'),
('0149', 'Yī Zhào Wéi Dé Huangpu Flagship', 'Shanghai', 'Huangpu District', '22744 Vanessa Ferry (Near Metro Station)'),
('0150', 'Wēi Kāng Jiangbei Flagship', 'Chongqing', 'Jiangbei District', '34183 Anna Forest Suite 015 (Near University)'),
('0151', 'Ào Měi Laoshan Flagship', 'Qingdao', 'Laoshan District', '3968 Michael River (Near University)'),
('0152', 'Jīn Shì Bǎo Putuo Flagship', 'Shanghai', 'Putuo District', '25677 Teresa Views Suite 521 (Near Shopping Mall)'),
('0153', 'Měi Gé Fēi Xicheng Flagship', 'Beijing', 'Xicheng District', '9687 Nicholas Lane (Near Shopping Mall)'),
('0154', 'Měi Gé Fēi Tongzhou Flagship', 'Beijing', 'Tongzhou District', '952 Knight Ways Suite 198 (Near Metro Station)'),
('0155', 'Wēi Kāng Nankai Flagship', 'Tianjin', 'Nankai District', '2039 Tanya Forges Suite 738 (Near University)'),
('0156', 'Jīn Shì Bǎo Wuhou Flagship', 'Chengdu', 'Wuhou District', '29112 Morris Pine (Near University)'),
('0157', 'Yī Zhào Wéi Dé Beibei Flagship', 'Chongqing', 'Beibei District', '761 John Islands Suite 654 (Near University)'),
('0158', 'Lì Měi Beilin Flagship', 'Xian', 'Beilin District', '15904 Randy Villages Suite 685 (Near Metro Station)'),
('0159', 'Lì Měi Yangpu Flagship', 'Shanghai', 'Yangpu District', '9443 Perry Village Suite 199 (Near University)'),
('0160', 'Lì Měi Shijingshan Flagship', 'Beijing', 'Shijingshan District', '962 Marshall Mountain (Near Metro Station)'),
('0161', 'Měi Gé Fēi Yuhuatai Flagship', 'Nanjing', 'Yuhuatai District', '23850 Daniel Row Suite 723 (Near University)'),
('0162', 'Wēi Kāng Fenghua Flagship', 'Ningbo', 'Fenghua District', '129 Jennifer Glen Suite 146 (Near Shopping Mall)'),
('0163', 'Lì Měi Huangdao Flagship', 'Qingdao', 'Huangdao District', '61764 Johnson Bypass (Near Shopping Mall)'),
('0164', 'Wēi Kāng Hongshan Flagship', 'Wuhan', 'Hongshan District', '18010 Melissa Shores (Near Metro Station)'),
('0165', 'Lì Měi Xishan Flagship', 'Wuxi', 'Xishan District', '2095 Alison Forest Apt. 343 (Near University)'),
('0166', 'Jiàn Lè Shijingshan Flagship', 'Beijing', 'Shijingshan District', '965 Hunter Ferry Suite 818 (Near Metro Station)'),
('0167', 'Ào Měi Yuhuatai Flagship', 'Nanjing', 'Yuhuatai District', '305 Ryan Roads Suite 717 (Near University)'),
('0168', 'Yī Zhào Wéi Dé Gongshu Flagship', 'Hangzhou', 'Gongshu District', '2731 Mckenzie Mountains Apt. 762 (Near Shopping Mall)'),
('0169', 'Wēi Ěr Shì Longgang Flagship', 'Shenzhen', 'Longgang District', '88313 Deanna Road (Near Shopping Mall)'),
('0170', 'Ào Měi Chengyang Flagship', 'Qingdao', 'Chengyang District', '82077 Sarah Lodge (Near Shopping Mall)'),
('0171', 'Yī Zhào Wéi Dé Nanhai Flagship', 'Foshan', 'Nanhai District', '088 Karen Isle Suite 168 (Near Shopping Mall)'),
('0172', 'Jiàn Lè Huangdao Flagship', 'Qingdao', 'Huangdao District', '4605 Jerome Manors Suite 567 (Near Metro Station)'),
('0173', 'Jīn Shì Bǎo Gulou Flagship', 'Nanjing', 'Gulou District', '39397 Erickson Motorway Apt. 575 (Near Shopping Mall)'),
('0174', 'Wēi Kāng Zhongshan Flagship', 'Dalian', 'Zhongshan District', '638 Daniel Trail (Near University)'),
('0175', 'Wēi Kāng Huqiu Flagship', 'Suzhou', 'Huqiu District', '7569 Kimberly Isle (Near Shopping Mall)'),
('0176', 'Wēi Kāng Hongkou Flagship', 'Shanghai', 'Hongkou District', '5937 Nathaniel Island Apt. 578 (Near University)'),
('0177', 'Yī Zhào Wéi Dé Shunde Flagship', 'Foshan', 'Shunde District', '74305 James Mountain Suite 496 (Near University)'),
('0178', 'Wēi Kāng Hongshan Flagship', 'Wuhan', 'Hongshan District', '60786 Butler Station Apt. 097 (Near Shopping Mall)'),
('0179', 'Jiàn Lè Liwan Flagship', 'Guangzhou', 'Liwan District', '9481 Eddie Oval (Near University)'),
('0180', 'Měi Gé Fēi Hedong Flagship', 'Tianjin', 'Hedong District', '68380 Peters Forest (Near Shopping Mall)'),
('0181', 'Wēi Ěr Shì Changning Flagship', 'Shanghai', 'Changning District', '153 Thomas Pass Apt. 835 (Near Metro Station)'),
('0182', 'Wēi Kāng Licheng Flagship', 'Jinan', 'Licheng District', '885 Mccoy Spring Apt. 162 (Near Metro Station)'),
('0183', 'Ào Měi Huangpu Flagship', 'Shanghai', 'Huangpu District', '592 Jeremy Trail (Near Metro Station)'),
('0184', 'Jīn Shì Bǎo Wuchang Flagship', 'Wuhan', 'Wuchang District', '75594 Brent Crest Apt. 091 (Near Shopping Mall)'),
('0185', 'Yī Zhào Wéi Dé Gulou Flagship', 'Nanjing', 'Gulou District', '67757 Nielsen Forest Apt. 778 (Near University)'),
('0186', 'Lì Měi Zhenhai Flagship', 'Ningbo', 'Zhenhai District', '658 Strickland Loop (Near University)'),
('0187', 'Lì Měi Jiangan Flagship', 'Wuhan', 'Jiangan District', '921 Flores Shoals Suite 953 (Near Metro Station)'),
('0188', 'Ào Měi Zhenhai Flagship', 'Ningbo', 'Zhenhai District', '687 Rodriguez Mountain Suite 039 (Near Shopping Mall)'),
('0189', 'Měi Gé Fēi Gaoming Flagship', 'Foshan', 'Gaoming District', '13571 Aguilar Prairie Apt. 582 (Near University)'),
('0190', 'Wēi Kāng Xuhui Flagship', 'Shanghai', 'Xuhui District', '79387 Parsons Valleys (Near Shopping Mall)'),
('0191', 'Lì Měi Wuchang Flagship', 'Wuhan', 'Wuchang District', '108 Phillip Centers Suite 801 (Near Metro Station)'),
('0192', 'Wēi Ěr Shì Jingan Flagship', 'Shanghai', 'Jingan District', '2604 Pamela Bypass (Near Metro Station)'),
('0193', 'Ào Měi Yangpu Flagship', 'Shanghai', 'Yangpu District', '7569 Tracy Via (Near University)'),
('0194', 'Jīn Shì Bǎo Beilin Flagship', 'Xian', 'Beilin District', '07939 Dillon Route Apt. 742 (Near University)'),
('0195', 'Wēi Kāng Songshanhu Flagship', 'Dongguan', 'Songshanhu District', '60535 Jennifer Glen Apt. 492 (Near University)'),
('0196', 'Jīn Shì Bǎo Shahekou Flagship', 'Dalian', 'Shahekou District', '9958 Audrey Shore (Near University)'),
('0197', 'Lì Měi Chengyang Flagship', 'Qingdao', 'Chengyang District', '558 Thomas Walks (Near Metro Station)'),
('0198', 'Jiàn Lè Xuhui Flagship', 'Shanghai', 'Xuhui District', '64704 Wells Pine Apt. 189 (Near Shopping Mall)'),
('0199', 'Lì Měi Haidian Flagship', 'Beijing', 'Haidian District', '31196 Brenda Courts Suite 339 (Near University)'),
('0200', 'Wēi Kāng Yanta Flagship', 'Xian', 'Yanta District', '222 Miller Plains (Near University)'),
('0201', 'Ào Měi Hexi Flagship', 'Tianjin', 'Hexi District', '5031 Smith Cliffs Suite 364 (Near Shopping Mall)'),
('0202', 'Měi Gé Fēi Shangjie Flagship', 'Zhengzhou', 'Shangjie District', '073 Johnson Crossroad Apt. 919 (Near University)'),
('0203', 'Jiàn Lè Huiji Flagship', 'Zhengzhou', 'Huiji District', '6621 Ann Corners (Near Metro Station)'),
('0204', 'Wēi Kāng Baqiao Flagship', 'Xian', 'Baqiao District', '643 John Branch Apt. 720 (Near University)'),
('0205', 'Měi Gé Fēi Baiyun Flagship', 'Guangzhou', 'Baiyun District', '199 Mary Springs Apt. 350 (Near Metro Station)'),
('0206', 'Jiàn Lè Licang Flagship', 'Qingdao', 'Licang District', '79959 Moore Wall Suite 178 (Near University)'),
('0207', 'Jiàn Lè Sanshui Flagship', 'Foshan', 'Sanshui District', '4934 Harrison Vista (Near Metro Station)'),
('0208', 'Wēi Kāng Tongan Flagship', 'Xiamen', 'Tongan District', '43759 Waters Lodge (Near Metro Station)'),
('0209', 'Yī Zhào Wéi Dé Xinwu Flagship', 'Wuxi', 'Xinwu District', '6233 Cassidy Shoals (Near Shopping Mall)'),
('0210', 'Yī Zhào Wéi Dé Qingyang Flagship', 'Chengdu', 'Qingyang District', '692 Nancy Plain (Near University)'),
('0211', 'Jiàn Lè Tianxin Flagship', 'Changsha', 'Tianxin District', '6938 Elizabeth Avenue Suite 643 (Near Metro Station)'),
('0212', 'Jiàn Lè Jianye Flagship', 'Nanjing', 'Jianye District', '76136 Stephen Isle Suite 143 (Near Metro Station)'),
('0213', 'Ào Měi Xuanwu Flagship', 'Nanjing', 'Xuanwu District', '338 Mia Village Apt. 968 (Near Shopping Mall)'),
('0214', 'Jīn Shì Bǎo Jianggan Flagship', 'Hangzhou', 'Jianggan District', '21539 Soto Island Suite 523 (Near Metro Station)'),
('0215', 'Yī Zhào Wéi Dé Baiyun Flagship', 'Guangzhou', 'Baiyun District', '56729 Wong River (Near University)'),
('0216', 'Wēi Kāng Longgang Flagship', 'Shenzhen', 'Longgang District', '6590 Richard Springs (Near University)'),
('0217', 'Lì Měi Chancheng Flagship', 'Foshan', 'Chancheng District', '2752 Young Prairie Apt. 103 (Near Metro Station)'),
('0218', 'Wēi Kāng Hexi Flagship', 'Tianjin', 'Hexi District', '16417 Chelsea Avenue (Near Shopping Mall)'),
('0219', 'Měi Gé Fēi Shapingba Flagship', 'Chongqing', 'Shapingba District', '168 Jessica Lights (Near University)'),
('0220', 'Wēi Ěr Shì Xinwu Flagship', 'Wuxi', 'Xinwu District', '408 Christy Route (Near University)'),
('0221', 'Jiàn Lè Changning Flagship', 'Shanghai', 'Changning District', '1263 Rachel Island (Near Metro Station)'),
('0222', 'Yī Zhào Wéi Dé Qinhuai Flagship', 'Nanjing', 'Qinhuai District', '867 Tricia Fields Suite 156 (Near Metro Station)'),
('0223', 'Yī Zhào Wéi Dé Jinshui Flagship', 'Zhengzhou', 'Jinshui District', '730 Denise Shore Apt. 736 (Near Metro Station)'),
('0224', 'Měi Gé Fēi Binjiang Flagship', 'Hangzhou', 'Binjiang District', '3258 Henderson Run (Near University)'),
('0225', 'Jiàn Lè Yuhuatai Flagship', 'Nanjing', 'Yuhuatai District', '464 Joshua Highway Suite 399 (Near University)'),
('0226', 'Lì Měi Baiyun Flagship', 'Guangzhou', 'Baiyun District', '0192 Barker Roads Suite 917 (Near Shopping Mall)'),
('0227', 'Měi Gé Fēi Wujiang Flagship', 'Suzhou', 'Wujiang District', '3715 Campbell Points Apt. 752 (Near Metro Station)'),
('0228', 'Lì Měi Hedong Flagship', 'Tianjin', 'Hedong District', '39372 Boyer Summit (Near Metro Station)'),
('0229', 'Jiàn Lè Jingan Flagship', 'Shanghai', 'Jingan District', '1178 Wendy Motorway (Near Metro Station)'),
('0230', 'Jīn Shì Bǎo Hexi Flagship', 'Tianjin', 'Hexi District', '628 Phillips Oval (Near University)'),
('0231', 'Ào Měi Hanyang Flagship', 'Wuhan', 'Hanyang District', '132 Alexander Trail Apt. 393 (Near Metro Station)'),
('0232', 'Měi Gé Fēi Wuchang Flagship', 'Wuhan', 'Wuchang District', '091 Kimberly Fields (Near Metro Station)'),
('0233', 'Jīn Shì Bǎo Fenghua Flagship', 'Ningbo', 'Fenghua District', '2699 Padilla Meadows (Near Shopping Mall)'),
('0234', 'Měi Gé Fēi Yanta Flagship', 'Xian', 'Yanta District', '625 Amber Tunnel (Near University)'),
('0235', 'Měi Gé Fēi Fengtai Flagship', 'Beijing', 'Fengtai District', '1324 Harper Pass (Near University)'),
('0236', 'Jiàn Lè Futian Flagship', 'Shenzhen', 'Futian District', '0853 Moody Station Apt. 748 (Near Metro Station)'),
('0237', 'Wēi Kāng Hedong Flagship', 'Tianjin', 'Hedong District', '79197 Christian Freeway (Near Metro Station)'),
('0238', 'Yī Zhào Wéi Dé Licang Flagship', 'Qingdao', 'Licang District', '205 Jimmy Ridges Apt. 447 (Near University)'),
('0239', 'Jiàn Lè Xishan Flagship', 'Wuxi', 'Xishan District', '6479 Laura Glens (Near Metro Station)'),
('0240', 'Jiàn Lè Yangpu Flagship', 'Shanghai', 'Yangpu District', '7244 Rebecca Vista Apt. 369 (Near University)'),
('0241', 'Jīn Shì Bǎo Jiangbei Flagship', 'Chongqing', 'Jiangbei District', '6806 Smith Green (Near Metro Station)'),
('0242', 'Lì Měi Shijingshan Flagship', 'Beijing', 'Shijingshan District', '182 Christopher Valley (Near Metro Station)'),
('0243', 'Wēi Kāng Lianhu Flagship', 'Xian', 'Lianhu District', '91428 Christine Mill (Near Shopping Mall)'),
('0244', 'Yī Zhào Wéi Dé Wuchang Flagship', 'Wuhan', 'Wuchang District', '142 Sean Glen Suite 068 (Near University)'),
('0245', 'Lì Měi Baoan Flagship', 'Shenzhen', 'Baoan District', '774 Brenda Island Apt. 224 (Near Shopping Mall)'),
('0246', 'Jīn Shì Bǎo Tongan Flagship', 'Xiamen', 'Tongan District', '25336 Ruben Crossroad (Near University)'),
('0247', 'Yī Zhào Wéi Dé Huishan Flagship', 'Wuxi', 'Huishan District', '482 Gordon Haven Apt. 784 (Near Shopping Mall)'),
('0248', 'Lì Měi Hanyang Flagship', 'Wuhan', 'Hanyang District', '42936 Colleen Neck Suite 413 (Near University)'),
('0249', 'Měi Gé Fēi Baiyun Flagship', 'Guangzhou', 'Baiyun District', '876 Bishop Keys (Near Shopping Mall)'),
('0250', 'Jīn Shì Bǎo Xicheng Flagship', 'Beijing', 'Xicheng District', '15803 Bolton Lakes (Near Metro Station)'),
('0251', 'Yī Zhào Wéi Dé Binhu Flagship', 'Wuxi', 'Binhu District', '2898 Bailey Fields (Near Shopping Mall)'),
('0252', 'Wēi Ěr Shì Shibei Flagship', 'Qingdao', 'Shibei District', '222 Jason Plains Apt. 601 (Near Shopping Mall)'),
('0253', 'Yī Zhào Wéi Dé Huishan Flagship', 'Wuxi', 'Huishan District', '2212 Nunez Rapid (Near University)'),
('0254', 'Jiàn Lè Yuexiu Flagship', 'Guangzhou', 'Yuexiu District', '893 Michael Trafficway (Near Metro Station)'),
('0255', 'Měi Gé Fēi Wujiang Flagship', 'Suzhou', 'Wujiang District', '464 Lisa Key (Near Shopping Mall)'),
('0256', 'Měi Gé Fēi Hongkou Flagship', 'Shanghai', 'Hongkou District', '3997 Daniel Passage Apt. 348 (Near Shopping Mall)'),
('0257', 'Ào Měi Jinniu Flagship', 'Chengdu', 'Jinniu District', '13324 Brittany Bridge (Near Metro Station)'),
('0258', 'Lì Měi Haicang Flagship', 'Xiamen', 'Haicang District', '043 Justin Pines Apt. 437 (Near Shopping Mall)'),
('0259', 'Wēi Ěr Shì Jinshui Flagship', 'Zhengzhou', 'Jinshui District', '7330 Pierce Course Apt. 613 (Near University)'),
('0260', 'Ào Měi Jiangan Flagship', 'Wuhan', 'Jiangan District', '9067 Heather Pass Apt. 637 (Near Shopping Mall)'),
('0261', 'Yī Zhào Wéi Dé Jianggan Flagship', 'Hangzhou', 'Jianggan District', '1046 Charles Rapids (Near Shopping Mall)'),
('0262', 'Yī Zhào Wéi Dé Qiaokou Flagship', 'Wuhan', 'Qiaokou District', '753 Murray Avenue (Near University)'),
('0263', 'Wēi Ěr Shì Nanan Flagship', 'Chongqing', 'Nanan District', '925 Jennifer Club (Near Metro Station)'),
('0264', 'Wēi Kāng Putuo Flagship', 'Shanghai', 'Putuo District', '628 Turner Forges (Near Shopping Mall)'),
('0265', 'Lì Měi Haicang Flagship', 'Xiamen', 'Haicang District', '8832 Gonzalez Place (Near Metro Station)'),
('0266', 'Wēi Ěr Shì Jinjiang Flagship', 'Chengdu', 'Jinjiang District', '0479 Jack Islands Suite 175 (Near Shopping Mall)'),
('0267', 'Měi Gé Fēi Jianye Flagship', 'Nanjing', 'Jianye District', '8311 Nicole Vista Apt. 924 (Near Metro Station)'),
('0268', 'Jīn Shì Bǎo Tongzhou Flagship', 'Beijing', 'Tongzhou District', '7750 Michael Mount (Near Metro Station)'),
('0269', 'Wēi Ěr Shì Shangcheng Flagship', 'Hangzhou', 'Shangcheng District', '3617 Coleman Falls (Near Shopping Mall)'),
('0270', 'Wēi Kāng Xicheng Flagship', 'Beijing', 'Xicheng District', '12834 Snyder Mission (Near University)'),
('0271', 'Lì Měi Laoshan Flagship', 'Qingdao', 'Laoshan District', '584 Deborah Hill Apt. 680 (Near University)'),
('0272', 'Ào Měi Xincheng Flagship', 'Xian', 'Xincheng District', '2863 Stephanie Street (Near Metro Station)'),
('0273', 'Wēi Kāng Shibei Flagship', 'Qingdao', 'Shibei District', '420 Jennifer Point (Near Shopping Mall)'),
('0274', 'Wēi Ěr Shì Xihu Flagship', 'Hangzhou', 'Xihu District', '61168 Brewer Mount Apt. 337 (Near University)'),
('0275', 'Jiàn Lè Kaifu Flagship', 'Changsha', 'Kaifu District', '15366 David Walks Apt. 564 (Near University)'),
('0276', 'Yī Zhào Wéi Dé Shapingba Flagship', 'Chongqing', 'Shapingba District', '33304 Martinez Neck Apt. 967 (Near University)'),
('0277', 'Ào Měi Shapingba Flagship', 'Chongqing', 'Shapingba District', '20949 York Extension Apt. 896 (Near Metro Station)'),
('0278', 'Ào Měi Fengtai Flagship', 'Beijing', 'Fengtai District', '4178 Howell Meadow (Near Shopping Mall)'),
('0279', 'Ào Měi Baqiao Flagship', 'Xian', 'Baqiao District', '282 Webster Plaza (Near Metro Station)'),
('0280', 'Jīn Shì Bǎo Nanshan Flagship', 'Shenzhen', 'Nanshan District', '4941 Monroe Branch Suite 414 (Near Metro Station)'),
('0281', 'Ào Měi Xiacheng Flagship', 'Hangzhou', 'Xiacheng District', '247 Wade Track (Near Metro Station)'),
('0282', 'Wēi Ěr Shì Xuanwu Flagship', 'Nanjing', 'Xuanwu District', '980 Jonathan Parkway (Near Metro Station)'),
('0283', 'Jīn Shì Bǎo Beibei Flagship', 'Chongqing', 'Beibei District', '4935 Lutz Inlet (Near Metro Station)'),
('0284', 'Wēi Ěr Shì Haidian Flagship', 'Beijing', 'Haidian District', '52554 Charles Harbors (Near Metro Station)'),
('0285', 'Měi Gé Fēi Binjiang Flagship', 'Hangzhou', 'Binjiang District', '8211 Zimmerman Burgs Suite 265 (Near University)'),
('0286', 'Měi Gé Fēi Tianqiao Flagship', 'Jinan', 'Tianqiao District', '4802 Andrew Overpass (Near University)'),
('0287', 'Ào Měi Tianqiao Flagship', 'Jinan', 'Tianqiao District', '344 Drew Island Suite 743 (Near Metro Station)'),
('0288', 'Měi Gé Fēi Xuhui Flagship', 'Shanghai', 'Xuhui District', '3194 Nathan Groves (Near Metro Station)'),
('0289', 'Měi Gé Fēi Chaoyang Flagship', 'Beijing', 'Chaoyang District', '1932 Bruce Rapids Apt. 223 (Near Shopping Mall)'),
('0290', 'Wēi Kāng Ganjingzi Flagship', 'Dalian', 'Ganjingzi District', '171 George Valley (Near Metro Station)'),
('0291', 'Yī Zhào Wéi Dé Haidian Flagship', 'Beijing', 'Haidian District', '43877 Patrick Oval (Near Shopping Mall)'),
('0292', 'Wēi Kāng Chenghua Flagship', 'Chengdu', 'Chenghua District', '98284 Jonathan Meadow (Near Metro Station)'),
('0293', 'Měi Gé Fēi Luohu Flagship', 'Shenzhen', 'Luohu District', '609 Jessica Pike Apt. 305 (Near Shopping Mall)'),
('0294', 'Yī Zhào Wéi Dé Wangcheng Flagship', 'Changsha', 'Wangcheng District', '27922 Kylie Fords (Near University)'),
('0295', 'Yī Zhào Wéi Dé Liangxi Flagship', 'Wuxi', 'Liangxi District', '887 Paula Row (Near University)'),
('0296', 'Wēi Kāng Shijingshan Flagship', 'Beijing', 'Shijingshan District', '9328 Ballard Squares (Near University)'),
('0297', 'Měi Gé Fēi Wangcheng Flagship', 'Changsha', 'Wangcheng District', '77365 Amanda Drive Suite 914 (Near University)'),
('0298', 'Jīn Shì Bǎo Jinshui Flagship', 'Zhengzhou', 'Jinshui District', '300 Martinez Viaduct (Near University)'),
('0299', 'Wēi Kāng Baqiao Flagship', 'Xian', 'Baqiao District', '01160 Hensley Hill (Near Metro Station)'),
('0300', 'Ào Měi Chaoyang Flagship', 'Beijing', 'Chaoyang District', '73928 Short River Suite 000 (Near Metro Station)'),
('0301', 'Jīn Shì Bǎo Jianggan Flagship', 'Hangzhou', 'Jianggan District', '37850 Williams Stravenue Apt. 104 (Near Metro Station)'),
('0302', 'Yī Zhào Wéi Dé Beilin Flagship', 'Xian', 'Beilin District', '79833 Joshua Branch Suite 873 (Near University)'),
('0303', 'Ào Měi Kaifu Flagship', 'Changsha', 'Kaifu District', '64414 Sandra View Suite 118 (Near Shopping Mall)'),
('0304', 'Měi Gé Fēi Liangxi Flagship', 'Wuxi', 'Liangxi District', '10626 Mccann Ferry (Near Shopping Mall)'),
('0305', 'Měi Gé Fēi Haicang Flagship', 'Xiamen', 'Haicang District', '54736 Craig Course Suite 574 (Near Metro Station)'),
('0306', 'Lì Měi Shahekou Flagship', 'Dalian', 'Shahekou District', '6692 Harris Rest Apt. 881 (Near Shopping Mall)'),
('0307', 'Ào Měi Chengyang Flagship', 'Qingdao', 'Chengyang District', '805 Watson Squares (Near University)'),
('0308', 'Lì Měi Huishan Flagship', 'Wuxi', 'Huishan District', '787 Nicholas Knolls Apt. 732 (Near Metro Station)'),
('0309', 'Ào Měi Wangcheng Flagship', 'Changsha', 'Wangcheng District', '0852 Donald Haven (Near Metro Station)'),
('0310', 'Ào Měi Licang Flagship', 'Qingdao', 'Licang District', '91387 Andrew Vista Apt. 801 (Near Shopping Mall)'),
('0311', 'Wēi Kāng Huiji Flagship', 'Zhengzhou', 'Huiji District', '7162 Thomas Tunnel Apt. 818 (Near Metro Station)'),
('0312', 'Wēi Kāng Shapingba Flagship', 'Chongqing', 'Shapingba District', '77231 Contreras Landing Apt. 552 (Near Shopping Mall)'),
('0313', 'Ào Měi Liwan Flagship', 'Guangzhou', 'Liwan District', '8405 Carter Camp (Near Shopping Mall)'),
('0314', 'Lì Měi Xishan Flagship', 'Wuxi', 'Xishan District', '872 Travis Ports Suite 155 (Near University)'),
('0315', 'Jīn Shì Bǎo Xuanwu Flagship', 'Nanjing', 'Xuanwu District', '731 Molina Lodge Apt. 546 (Near Shopping Mall)'),
('0316', 'Yī Zhào Wéi Dé Furong Flagship', 'Changsha', 'Furong District', '8928 Mark Parkway Apt. 947 (Near Metro Station)'),
('0317', 'Měi Gé Fēi Jinjiang Flagship', 'Chengdu', 'Jinjiang District', '58698 Cole Spur Apt. 841 (Near Metro Station)'),
('0318', 'Ào Měi Yuelu Flagship', 'Changsha', 'Yuelu District', '09652 Brown Loop Suite 165 (Near Shopping Mall)'),
('0319', 'Yī Zhào Wéi Dé Jiangan Flagship', 'Wuhan', 'Jiangan District', '11413 Moore Pine Suite 151 (Near Shopping Mall)'),
('0320', 'Lì Měi Beilin Flagship', 'Xian', 'Beilin District', '54987 Rachel Ranch Suite 119 (Near Metro Station)'),
('0321', 'Měi Gé Fēi Xinwu Flagship', 'Wuxi', 'Xinwu District', '73569 David Squares Suite 033 (Near Shopping Mall)'),
('0322', 'Lì Měi Yuzhong Flagship', 'Chongqing', 'Yuzhong District', '063 Torres Village (Near Shopping Mall)'),
('0323', 'Wēi Kāng Yuhuatai Flagship', 'Nanjing', 'Yuhuatai District', '8173 Marsh Port (Near Metro Station)'),
('0324', 'Wēi Kāng Binhu Flagship', 'Wuxi', 'Binhu District', '29887 Kelly Ville (Near Shopping Mall)'),
('0325', 'Jīn Shì Bǎo Huangdao Flagship', 'Qingdao', 'Huangdao District', '55972 Destiny Ramp Apt. 722 (Near Metro Station)'),
('0326', 'Měi Gé Fēi Jiulongpo Flagship', 'Chongqing', 'Jiulongpo District', '7354 Lozano Estates (Near University)'),
('0327', 'Wēi Kāng Shibei Flagship', 'Qingdao', 'Shibei District', '12439 Russell Course Suite 261 (Near Shopping Mall)'),
('0328', 'Lì Měi Xicheng Flagship', 'Beijing', 'Xicheng District', '92674 Gary Lock (Near University)'),
('0329', 'Yī Zhào Wéi Dé Wujiang Flagship', 'Suzhou', 'Wujiang District', '68656 Jonathan Crest Suite 169 (Near Metro Station)'),
('0330', 'Lì Měi Lianhu Flagship', 'Xian', 'Lianhu District', '830 Kevin Isle (Near Metro Station)'),
('0331', 'Jīn Shì Bǎo Changning Flagship', 'Shanghai', 'Changning District', '2238 Donna Prairie Suite 528 (Near Metro Station)'),
('0332', 'Wēi Kāng Laoshan Flagship', 'Qingdao', 'Laoshan District', '2994 Briana Unions (Near Shopping Mall)'),
('0333', 'Měi Gé Fēi Yuexiu Flagship', 'Guangzhou', 'Yuexiu District', '959 Keith Plains Apt. 591 (Near University)'),
('0334', 'Yī Zhào Wéi Dé Wuzhong Flagship', 'Suzhou', 'Wuzhong District', '901 Reynolds Valley (Near Shopping Mall)'),
('0335', 'Lì Měi Liwan Flagship', 'Guangzhou', 'Liwan District', '5456 Wright Glens (Near University)'),
('0336', 'Jiàn Lè Xicheng Flagship', 'Beijing', 'Xicheng District', '67483 Wise Garden (Near University)'),
('0337', 'Wēi Ěr Shì Changqing Flagship', 'Jinan', 'Changqing District', '30992 Murray Club Suite 771 (Near University)'),
('0338', 'Lì Měi Xuhui Flagship', 'Shanghai', 'Xuhui District', '5303 Michael Curve Suite 678 (Near Shopping Mall)'),
('0339', 'Yī Zhào Wéi Dé Xuanwu Flagship', 'Nanjing', 'Xuanwu District', '847 Vasquez Meadow Suite 863 (Near Shopping Mall)'),
('0340', 'Wēi Ěr Shì Yantian Flagship', 'Shenzhen', 'Yantian District', '5009 Jacob Field Suite 025 (Near University)'),
('0341', 'Jiàn Lè Qingyang Flagship', 'Chengdu', 'Qingyang District', '293 King Squares (Near University)'),
('0342', 'Jiàn Lè Wuhou Flagship', 'Chengdu', 'Wuhou District', '289 James Passage (Near University)'),
('0343', 'Wēi Kāng Yangpu Flagship', 'Shanghai', 'Yangpu District', '8993 Manuel Wall Suite 596 (Near Shopping Mall)'),
('0344', 'Jiàn Lè Shizhong Flagship', 'Jinan', 'Shizhong District', '78325 Reid Dam (Near Metro Station)'),
('0345', 'Yī Zhào Wéi Dé Huaiyin Flagship', 'Jinan', 'Huaiyin District', '986 Scott Prairie Apt. 486 (Near Metro Station)'),
('0346', 'Jīn Shì Bǎo Dongcheng Flagship', 'Dongguan', 'Dongcheng District', '15318 Anderson Squares (Near University)'),
('0347', 'Jiàn Lè Zhongyuan Flagship', 'Zhengzhou', 'Zhongyuan District', '300 Duran Pass (Near Metro Station)'),
('0348', 'Jiàn Lè Wanjiang Flagship', 'Dongguan', 'Wanjiang District', '133 Jones Roads (Near University)'),
('0349', 'Wēi Ěr Shì Shangcheng Flagship', 'Hangzhou', 'Shangcheng District', '124 Figueroa Mews Apt. 260 (Near Shopping Mall)'),
('0350', 'Lì Měi Kaifu Flagship', 'Changsha', 'Kaifu District', '00276 Campbell Expressway (Near Shopping Mall)'),
('0351', 'Wēi Ěr Shì Siming Flagship', 'Xiamen', 'Siming District', '323 Michael Port Apt. 819 (Near Metro Station)'),
('0352', 'Yī Zhào Wéi Dé Qinhuai Flagship', 'Nanjing', 'Qinhuai District', '06317 Lauren Street Apt. 611 (Near Metro Station)'),
('0353', 'Lì Měi Huangpu Flagship', 'Shanghai', 'Huangpu District', '461 Jones Courts Suite 812 (Near Shopping Mall)'),
('0354', 'Jīn Shì Bǎo Baqiao Flagship', 'Xian', 'Baqiao District', '3447 Fitzgerald Ridges (Near Metro Station)'),
('0355', 'Lì Měi Huaiyin Flagship', 'Jinan', 'Huaiyin District', '548 Brown Inlet (Near Shopping Mall)'),
('0356', 'Jīn Shì Bǎo Longquanyi Flagship', 'Chengdu', 'Longquanyi District', '261 Angela Lane Apt. 777 (Near Metro Station)'),
('0357', 'Měi Gé Fēi Beilin Flagship', 'Xian', 'Beilin District', '6766 Mitchell Underpass Apt. 000 (Near Shopping Mall)'),
('0358', 'Wēi Ěr Shì Xiangan Flagship', 'Xiamen', 'Xiangan District', '880 Smith Passage Apt. 988 (Near Metro Station)'),
('0359', 'Měi Gé Fēi Chenghua Flagship', 'Chengdu', 'Chenghua District', '86000 Brandon Motorway Apt. 639 (Near University)'),
('0360', 'Jīn Shì Bǎo Guancheng Flagship', 'Zhengzhou', 'Guancheng District', '98075 Julia Plains Apt. 513 (Near Shopping Mall)'),
('0361', 'Jiàn Lè Shapingba Flagship', 'Chongqing', 'Shapingba District', '092 Tasha Island Apt. 485 (Near University)'),
('0362', 'Jīn Shì Bǎo Huaiyin Flagship', 'Jinan', 'Huaiyin District', '765 Rivera Brooks Suite 756 (Near Metro Station)'),
('0363', 'Lì Měi Nankai Flagship', 'Tianjin', 'Nankai District', '99692 Chambers Junctions Suite 827 (Near Metro Station)'),
('0364', 'Jīn Shì Bǎo Chenghua Flagship', 'Chengdu', 'Chenghua District', '8621 Todd Parkways Apt. 535 (Near Metro Station)'),
('0365', 'Jīn Shì Bǎo Shijingshan Flagship', 'Beijing', 'Shijingshan District', '60260 Mcdaniel Lakes (Near Metro Station)'),
('0366', 'Měi Gé Fēi Hanyang Flagship', 'Wuhan', 'Hanyang District', '0455 Perez Hill Suite 893 (Near Shopping Mall)'),
('0367', 'Jīn Shì Bǎo Kaifu Flagship', 'Changsha', 'Kaifu District', '0329 Ricardo Hollow Suite 076 (Near Shopping Mall)'),
('0368', 'Ào Měi Songshanhu Flagship', 'Dongguan', 'Songshanhu District', '57178 Fox Plaza (Near University)'),
('0369', 'Jīn Shì Bǎo Hongkou Flagship', 'Shanghai', 'Hongkou District', '535 Brendan Walk (Near Shopping Mall)'),
('0370', 'Jīn Shì Bǎo Laoshan Flagship', 'Qingdao', 'Laoshan District', '7140 Grant Crescent Suite 172 (Near Metro Station)'),
('0371', 'Yī Zhào Wéi Dé Laoshan Flagship', 'Qingdao', 'Laoshan District', '1029 Whitehead Shore Suite 678 (Near University)'),
('0372', 'Jiàn Lè Dongcheng Flagship', 'Beijing', 'Dongcheng District', '67477 Campbell Station (Near University)'),
('0373', 'Lì Měi Chenghua Flagship', 'Chengdu', 'Chenghua District', '851 Taylor Tunnel Suite 856 (Near University)'),
('0374', 'Wēi Ěr Shì Shijingshan Flagship', 'Beijing', 'Shijingshan District', '039 Watts Valley (Near Metro Station)'),
('0375', 'Jīn Shì Bǎo Xuhui Flagship', 'Shanghai', 'Xuhui District', '301 Patrick Unions (Near University)'),
('0376', 'Yī Zhào Wéi Dé Jinshui Flagship', 'Zhengzhou', 'Jinshui District', '26877 Coleman Knoll Apt. 050 (Near Shopping Mall)'),
('0377', 'Měi Gé Fēi Xishan Flagship', 'Wuxi', 'Xishan District', '8257 Aguirre Drive Apt. 856 (Near Shopping Mall)'),
('0378', 'Yī Zhào Wéi Dé Sanshui Flagship', 'Foshan', 'Sanshui District', '2524 Rachel Green (Near University)'),
('0379', 'Yī Zhào Wéi Dé Huli Flagship', 'Xiamen', 'Huli District', '752 Hancock Flats (Near Metro Station)'),
('0380', 'Měi Gé Fēi Luohu Flagship', 'Shenzhen', 'Luohu District', '4041 Anne Freeway Suite 901 (Near Shopping Mall)'),
('0381', 'Ào Měi Tongzhou Flagship', 'Beijing', 'Tongzhou District', '2399 Henderson Radial (Near University)'),
('0382', 'Jīn Shì Bǎo Jingan Flagship', 'Shanghai', 'Jingan District', '49560 Schmitt Heights (Near Metro Station)'),
('0383', 'Lì Měi Jimei Flagship', 'Xiamen', 'Jimei District', '77712 Thomas Cape Apt. 118 (Near Metro Station)'),
('0384', 'Wēi Ěr Shì Haishu Flagship', 'Ningbo', 'Haishu District', '4561 Valerie Trafficway Suite 780 (Near Metro Station)'),
('0385', 'Ào Měi Jiangbei Flagship', 'Chongqing', 'Jiangbei District', '4575 Amy Skyway Suite 493 (Near University)'),
('0386', 'Jīn Shì Bǎo Xicheng Flagship', 'Beijing', 'Xicheng District', '653 Carr Pass Apt. 040 (Near Metro Station)'),
('0387', 'Měi Gé Fēi Yanta Flagship', 'Xian', 'Yanta District', '2722 Brittany Court Apt. 900 (Near Metro Station)'),
('0388', 'Měi Gé Fēi Jimei Flagship', 'Xiamen', 'Jimei District', '4646 Chad Port (Near University)'),
('0389', 'Wēi Ěr Shì Jinshui Flagship', 'Zhengzhou', 'Jinshui District', '50283 Barber Fort (Near Shopping Mall)'),
('0390', 'Jīn Shì Bǎo Yinzhou Flagship', 'Ningbo', 'Yinzhou District', '1104 Bowers Groves (Near University)'),
('0391', 'Jīn Shì Bǎo Tianhe Flagship', 'Guangzhou', 'Tianhe District', '763 Christopher Knolls (Near Shopping Mall)'),
('0392', 'Lì Měi Laoshan Flagship', 'Qingdao', 'Laoshan District', '398 Rodriguez Meadows Suite 600 (Near Metro Station)'),
('0393', 'Jīn Shì Bǎo Yangpu Flagship', 'Shanghai', 'Yangpu District', '64210 David Causeway Apt. 952 (Near Metro Station)'),
('0394', 'Lì Měi Shahekou Flagship', 'Dalian', 'Shahekou District', '8293 Jennifer Islands (Near University)'),
('0395', 'Měi Gé Fēi Laoshan Flagship', 'Qingdao', 'Laoshan District', '12002 Moreno Stream (Near University)'),
('0396', 'Jiàn Lè Heping Flagship', 'Tianjin', 'Heping District', '89085 Matthew Place Suite 255 (Near University)'),
('0397', 'Yī Zhào Wéi Dé Hongkou Flagship', 'Shanghai', 'Hongkou District', '6068 Guerrero Fields (Near Metro Station)'),
('0398', 'Měi Gé Fēi Luohu Flagship', 'Shenzhen', 'Luohu District', '18670 Carolyn Camp (Near University)'),
('0399', 'Lì Měi Jinshui Flagship', 'Zhengzhou', 'Jinshui District', '2384 Mary Drive Apt. 922 (Near University)'),
('0400', 'Měi Gé Fēi Hexi Flagship', 'Tianjin', 'Hexi District', '4337 Bray Roads Suite 591 (Near University)'),
('0401', 'Wēi Ěr Shì Ganjingzi Flagship', 'Dalian', 'Ganjingzi District', '1234 Robinson Crossroad (Near Shopping Mall)'),
('0402', 'Měi Gé Fēi Jiangbei Flagship', 'Chongqing', 'Jiangbei District', '0957 Kayla Land Apt. 716 (Near Shopping Mall)'),
('0403', 'Jiàn Lè Baiyun Flagship', 'Guangzhou', 'Baiyun District', '79836 Brian Courts (Near Shopping Mall)'),
('0404', 'Yī Zhào Wéi Dé Huiji Flagship', 'Zhengzhou', 'Huiji District', '7397 Holly Pines (Near University)'),
('0405', 'Wēi Ěr Shì Nanshan Flagship', 'Shenzhen', 'Nanshan District', '946 Ferguson Heights (Near University)'),
('0406', 'Yī Zhào Wéi Dé Hongkou Flagship', 'Shanghai', 'Hongkou District', '3069 Simmons Squares Apt. 267 (Near Metro Station)'),
('0407', 'Měi Gé Fēi Lixia Flagship', 'Jinan', 'Lixia District', '911 Rachel Forks Apt. 244 (Near University)'),
('0408', 'Měi Gé Fēi Fenghua Flagship', 'Ningbo', 'Fenghua District', '683 Joseph Rue (Near University)'),
('0409', 'Ào Měi Hanyang Flagship', 'Wuhan', 'Hanyang District', '6518 Brown Passage Apt. 272 (Near Metro Station)'),
('0410', 'Lì Měi Jiangbei Flagship', 'Ningbo', 'Jiangbei District', '704 Ward Summit (Near Shopping Mall)'),
('0411', 'Jiàn Lè Hebei Flagship', 'Tianjin', 'Hebei District', '2619 Sherman Hills Apt. 572 (Near Metro Station)'),
('0412', 'Wēi Kāng Shizhong Flagship', 'Jinan', 'Shizhong District', '38999 Sergio Turnpike (Near Shopping Mall)'),
('0413', 'Wēi Ěr Shì Tianqiao Flagship', 'Jinan', 'Tianqiao District', '47515 Grimes Fort Apt. 669 (Near Shopping Mall)'),
('0414', 'Yī Zhào Wéi Dé Xuhui Flagship', 'Shanghai', 'Xuhui District', '67497 Roger Turnpike (Near Metro Station)'),
('0415', 'Měi Gé Fēi Tianqiao Flagship', 'Jinan', 'Tianqiao District', '34894 White Hill Apt. 884 (Near Shopping Mall)'),
('0416', 'Lì Měi Haizhu Flagship', 'Guangzhou', 'Haizhu District', '452 Morgan Loaf (Near Shopping Mall)'),
('0417', 'Wēi Ěr Shì Jiulongpo Flagship', 'Chongqing', 'Jiulongpo District', '118 Robert Summit (Near Metro Station)'),
('0418', 'Wēi Ěr Shì Jinjiang Flagship', 'Chengdu', 'Jinjiang District', '45470 Butler Village Apt. 475 (Near Shopping Mall)'),
('0419', 'Wēi Ěr Shì Furong Flagship', 'Changsha', 'Furong District', '2589 Burke Glens Suite 145 (Near Metro Station)'),
('0420', 'Jiàn Lè Beilin Flagship', 'Xian', 'Beilin District', '61306 Santana Throughway (Near University)'),
('0421', 'Yī Zhào Wéi Dé Binjiang Flagship', 'Hangzhou', 'Binjiang District', '261 Sarah Mission Suite 362 (Near Shopping Mall)'),
('0422', 'Lì Měi Hebei Flagship', 'Tianjin', 'Hebei District', '576 Sean Turnpike Suite 432 (Near Metro Station)'),
('0423', 'Lì Měi Xiangcheng Flagship', 'Suzhou', 'Xiangcheng District', '7639 Juan Underpass (Near University)'),
('0424', 'Wēi Ěr Shì Fengtai Flagship', 'Beijing', 'Fengtai District', '29702 Sanchez Corners (Near Shopping Mall)'),
('0425', 'Jiàn Lè Luohu Flagship', 'Shenzhen', 'Luohu District', '681 Williams Parkways Suite 340 (Near University)'),
('0426', 'Yī Zhào Wéi Dé Shunde Flagship', 'Foshan', 'Shunde District', '3518 Jill Corners (Near Shopping Mall)'),
('0427', 'Yī Zhào Wéi Dé Jiulongpo Flagship', 'Chongqing', 'Jiulongpo District', '675 Harris Plains (Near Shopping Mall)'),
('0428', 'Wēi Ěr Shì Gaoming Flagship', 'Foshan', 'Gaoming District', '23146 Rebecca Points (Near Shopping Mall)'),
('0429', 'Yī Zhào Wéi Dé Shibei Flagship', 'Qingdao', 'Shibei District', '92958 Zachary Way (Near University)'),
('0430', 'Jīn Shì Bǎo Longquanyi Flagship', 'Chengdu', 'Longquanyi District', '8123 Walker Meadows (Near Shopping Mall)'),
('0431', 'Ào Měi Nanshan Flagship', 'Shenzhen', 'Nanshan District', '84668 Sanchez Run (Near Shopping Mall)'),
('0432', 'Wēi Kāng Jingan Flagship', 'Shanghai', 'Jingan District', '760 Wesley Crest (Near Metro Station)'),
('0433', 'Ào Měi Longgang Flagship', 'Shenzhen', 'Longgang District', '58690 Nicole Islands (Near University)'),
('0434', 'Měi Gé Fēi Wujiang Flagship', 'Suzhou', 'Wujiang District', '7612 Zachary Prairie (Near Metro Station)'),
('0435', 'Yī Zhào Wéi Dé Shizhong Flagship', 'Jinan', 'Shizhong District', '74505 Ross Crossing Apt. 826 (Near University)'),
('0436', 'Yī Zhào Wéi Dé Huli Flagship', 'Xiamen', 'Huli District', '6851 Connie Groves Apt. 973 (Near University)'),
('0437', 'Wēi Ěr Shì Beibei Flagship', 'Chongqing', 'Beibei District', '082 Welch Fall Apt. 751 (Near Shopping Mall)'),
('0438', 'Jīn Shì Bǎo Zhenhai Flagship', 'Ningbo', 'Zhenhai District', '31773 Nelson Plaza (Near University)'),
('0439', 'Ào Měi Binhu Flagship', 'Wuxi', 'Binhu District', '5299 Christopher Radial (Near Metro Station)'),
('0440', 'Jīn Shì Bǎo Xicheng Flagship', 'Beijing', 'Xicheng District', '967 Lisa Glens Apt. 658 (Near University)'),
('0441', 'Jīn Shì Bǎo Hexi Flagship', 'Tianjin', 'Hexi District', '834 Russell Dam (Near Metro Station)'),
('0442', 'Ào Měi Dongcheng Flagship', 'Beijing', 'Dongcheng District', '1152 Steven Creek Suite 732 (Near Metro Station)'),
('0443', 'Měi Gé Fēi Longgang Flagship', 'Shenzhen', 'Longgang District', '5680 Jaclyn Terrace (Near Metro Station)'),
('0444', 'Wēi Ěr Shì Lixia Flagship', 'Jinan', 'Lixia District', '85466 Alejandro Coves Suite 158 (Near Metro Station)'),
('0445', 'Wēi Kāng Shapingba Flagship', 'Chongqing', 'Shapingba District', '18651 Gutierrez Islands Suite 860 (Near University)'),
('0446', 'Lì Měi Longquanyi Flagship', 'Chengdu', 'Longquanyi District', '103 Melissa Trafficway (Near Metro Station)'),
('0447', 'Wēi Kāng Baoan Flagship', 'Shenzhen', 'Baoan District', '7111 Kristen Dam Apt. 634 (Near University)'),
('0448', 'Wēi Ěr Shì Licheng Flagship', 'Jinan', 'Licheng District', '05634 Derek Ridges Suite 991 (Near Metro Station)'),
('0449', 'Jīn Shì Bǎo Dongcheng Flagship', 'Beijing', 'Dongcheng District', '7293 Mayo Gateway Suite 340 (Near Shopping Mall)'),
('0450', 'Jīn Shì Bǎo Hongkou Flagship', 'Shanghai', 'Hongkou District', '790 Turner Ports Suite 287 (Near University)'),
('0451', 'Wēi Ěr Shì Dongcheng Flagship', 'Dongguan', 'Dongcheng District', '40778 Lopez Brooks (Near Metro Station)'),
('0452', 'Jīn Shì Bǎo Xigang Flagship', 'Dalian', 'Xigang District', '13404 James Harbors Apt. 371 (Near Shopping Mall)'),
('0453', 'Wēi Kāng Jingan Flagship', 'Shanghai', 'Jingan District', '4978 Jennifer Walk Suite 023 (Near Metro Station)'),
('0454', 'Ào Měi Gongshu Flagship', 'Hangzhou', 'Gongshu District', '4252 Kelly Greens (Near Shopping Mall)'),
('0455', 'Jiàn Lè Chaoyang Flagship', 'Beijing', 'Chaoyang District', '2654 Carlos Glens Suite 088 (Near Metro Station)'),
('0456', 'Wēi Ěr Shì Jianghan Flagship', 'Wuhan', 'Jianghan District', '277 Kellie Forges Apt. 003 (Near Metro Station)'),
('0457', 'Wēi Ěr Shì Sanshui Flagship', 'Foshan', 'Sanshui District', '07275 Christopher Field (Near Metro Station)'),
('0458', 'Wēi Kāng Nanan Flagship', 'Chongqing', 'Nanan District', '12616 Andrew Spring Suite 487 (Near Metro Station)'),
('0459', 'Wēi Kāng Gongshu Flagship', 'Hangzhou', 'Gongshu District', '9201 Ross Coves Apt. 520 (Near Shopping Mall)'),
('0460', 'Wēi Ěr Shì Beilun Flagship', 'Ningbo', 'Beilun District', '6665 Reyes Crest Suite 174 (Near Shopping Mall)'),
('0461', 'Yī Zhào Wéi Dé Changning Flagship', 'Shanghai', 'Changning District', '569 Sosa Walks (Near Shopping Mall)'),
('0462', 'Ào Měi Jingan Flagship', 'Shanghai', 'Jingan District', '04997 Edward Manors Suite 881 (Near University)'),
('0463', 'Wēi Kāng Songshanhu Flagship', 'Dongguan', 'Songshanhu District', '899 Villegas Mall (Near Shopping Mall)'),
('0464', 'Lì Měi Longquanyi Flagship', 'Chengdu', 'Longquanyi District', '6530 Gilmore Union (Near Shopping Mall)'),
('0465', 'Jiàn Lè Lianhu Flagship', 'Xian', 'Lianhu District', '420 Caitlin Locks Suite 171 (Near Metro Station)'),
('0466', 'Ào Měi Putuo Flagship', 'Shanghai', 'Putuo District', '570 Howell Centers Apt. 111 (Near University)'),
('0467', 'Jiàn Lè Liangxi Flagship', 'Wuxi', 'Liangxi District', '7470 Lauren Land Suite 163 (Near Metro Station)'),
('0468', 'Yī Zhào Wéi Dé Nankai Flagship', 'Tianjin', 'Nankai District', '480 Crystal Crescent (Near Metro Station)'),
('0469', 'Lì Měi Putuo Flagship', 'Shanghai', 'Putuo District', '46609 Garcia Mount Suite 032 (Near Metro Station)'),
('0470', 'Měi Gé Fēi Hongkou Flagship', 'Shanghai', 'Hongkou District', '6982 Graves Inlet Apt. 015 (Near Shopping Mall)'),
('0471', 'Ào Měi Songshanhu Flagship', 'Dongguan', 'Songshanhu District', '39855 Smith Row Suite 844 (Near Metro Station)'),
('0472', 'Jīn Shì Bǎo Shinan Flagship', 'Qingdao', 'Shinan District', '7096 Ryan Parkway Suite 281 (Near Shopping Mall)'),
('0473', 'Wēi Ěr Shì Wuhou Flagship', 'Chengdu', 'Wuhou District', '679 Marsh Meadow (Near Metro Station)'),
('0474', 'Ào Měi Hongkou Flagship', 'Shanghai', 'Hongkou District', '855 Howard Shoals (Near Metro Station)'),
('0475', 'Wēi Kāng Huishan Flagship', 'Wuxi', 'Huishan District', '12032 Christopher Skyway (Near University)'),
('0476', 'Wēi Ěr Shì Hongkou Flagship', 'Shanghai', 'Hongkou District', '1791 Gillespie Brook Suite 955 (Near Metro Station)'),
('0477', 'Wēi Ěr Shì Qingyang Flagship', 'Chengdu', 'Qingyang District', '09320 Bradshaw Island Suite 780 (Near Shopping Mall)'),
('0478', 'Yī Zhào Wéi Dé Zhongshan Flagship', 'Dalian', 'Zhongshan District', '4245 Phillip Parkways Suite 236 (Near Shopping Mall)'),
('0479', 'Jiàn Lè Baqiao Flagship', 'Xian', 'Baqiao District', '5905 Angela Viaduct (Near Metro Station)'),
('0480', 'Lì Měi Ganjingzi Flagship', 'Dalian', 'Ganjingzi District', '26253 Parker Flats (Near University)'),
('0481', 'Jiàn Lè Jianye Flagship', 'Nanjing', 'Jianye District', '044 Steven Circles Apt. 007 (Near Metro Station)'),
('0482', 'Wēi Ěr Shì Hongkou Flagship', 'Shanghai', 'Hongkou District', '654 James Highway (Near Shopping Mall)'),
('0483', 'Jīn Shì Bǎo Qingyang Flagship', 'Chengdu', 'Qingyang District', '37769 Henderson Camp (Near University)'),
('0484', 'Jīn Shì Bǎo Yanta Flagship', 'Xian', 'Yanta District', '7847 Mitchell Shores Apt. 442 (Near University)'),
('0485', 'Wēi Kāng Gusu Flagship', 'Suzhou', 'Gusu District', '1770 Heather Islands Apt. 856 (Near Metro Station)'),
('0486', 'Wēi Kāng Huangdao Flagship', 'Qingdao', 'Huangdao District', '114 Joseph Club Suite 833 (Near Shopping Mall)'),
('0487', 'Yī Zhào Wéi Dé Haicang Flagship', 'Xiamen', 'Haicang District', '224 Silva Branch Apt. 957 (Near Shopping Mall)'),
('0488', 'Wēi Kāng Jiangan Flagship', 'Wuhan', 'Jiangan District', '06345 Richards Harbor (Near University)'),
('0489', 'Lì Měi Haizhu Flagship', 'Guangzhou', 'Haizhu District', '06773 Jose Port Apt. 137 (Near Metro Station)'),
('0490', 'Jīn Shì Bǎo Hebei Flagship', 'Tianjin', 'Hebei District', '97855 Atkinson Springs Apt. 432 (Near Shopping Mall)'),
('0491', 'Ào Měi Longgang Flagship', 'Shenzhen', 'Longgang District', '4146 Ramirez Drive (Near Metro Station)'),
('0492', 'Ào Měi Hanyang Flagship', 'Wuhan', 'Hanyang District', '916 Benjamin Harbors (Near Shopping Mall)'),
('0493', 'Wēi Ěr Shì Yantian Flagship', 'Shenzhen', 'Yantian District', '2576 Harris Knolls (Near University)'),
('0494', 'Ào Měi Hedong Flagship', 'Tianjin', 'Hedong District', '81345 Angela Circles (Near Shopping Mall)'),
('0495', 'Ào Měi Jianggan Flagship', 'Hangzhou', 'Jianggan District', '9251 Williams Island (Near Metro Station)'),
('0496', 'Jiàn Lè Zhongyuan Flagship', 'Zhengzhou', 'Zhongyuan District', '4341 Wong Forks (Near Metro Station)'),
('0497', 'Yī Zhào Wéi Dé Hongqiao Flagship', 'Tianjin', 'Hongqiao District', '5508 Steven Glen Suite 945 (Near University)'),
('0498', 'Wēi Kāng Zhongyuan Flagship', 'Zhengzhou', 'Zhongyuan District', '60944 William Forge (Near University)'),
('0499', 'Jiàn Lè Dongcheng Flagship', 'Dongguan', 'Dongcheng District', '15013 David Flat (Near Metro Station)'),
('0500', 'Wēi Kāng Wuhou Flagship', 'Chengdu', 'Wuhou District', '063 Martinez Avenue (Near Metro Station)');